spring:
  datasource:
    url: jdbc:mysql://database-1.cabiyddep9nf.us-east-2.rds.amazonaws.com:3306/carrot_db?useSSL=false&useUnicode=true&serverTime
    username : admin
    password : tlacksgml12?
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
    properties:
      hibernate:
        format_sql: true
